# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess


class Ui_admin(object):
    def chuyenDenDanhSachNguoiTimViec(self):
        subprocess.run(["python", "tuyendung_QuanLyNguoiTimViec.py"])
    def chuyenDenDSNhaTuyenDung(self):
        subprocess.run(["python", "timviec_DanhSachNhaTuyenDung.py"])
    def moQuanLyCongViec(self):
        subprocess.run(["python", "admin_QuanLyCongViec.py"])

    def setupUi(self, admin):
        admin.setObjectName("admin")
        admin.resize(371, 266)
        self.centralwidget = QtWidgets.QWidget(parent=admin)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_listnguoitimviec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_listnguoitimviec.setGeometry(QtCore.QRect(80, 20, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_listnguoitimviec.setFont(font)
        self.bt_listnguoitimviec.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_listnguoitimviec.setObjectName("bt_listnguoitimviec")
        self.bt_listnhatuyendung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_listnhatuyendung.setGeometry(QtCore.QRect(80, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_listnhatuyendung.setFont(font)
        self.bt_listnhatuyendung.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_listnhatuyendung.setObjectName("bt_listnhatuyendung")
        self.bt_listcongviec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_listcongviec.setGeometry(QtCore.QRect(80, 160, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_listcongviec.setFont(font)
        self.bt_listcongviec.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_listcongviec.setObjectName("bt_listcongviec")
        admin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=admin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 371, 26))
        self.menubar.setObjectName("menubar")
        admin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=admin)
        self.statusbar.setObjectName("statusbar")
        admin.setStatusBar(self.statusbar)

        self.retranslateUi(admin)
        QtCore.QMetaObject.connectSlotsByName(admin)
        self.bt_listcongviec.clicked.connect(self.moQuanLyCongViec)
        self.bt_listnhatuyendung.clicked.connect(self.chuyenDenDSNhaTuyenDung)
        self.bt_listnguoitimviec.clicked.connect(self.chuyenDenDanhSachNguoiTimViec)

    def retranslateUi(self, admin):
        _translate = QtCore.QCoreApplication.translate
        admin.setWindowTitle(_translate("admin", "Quản trị viên"))
        self.bt_listnguoitimviec.setText(_translate("admin", "Người tìm việc"))
        self.bt_listnhatuyendung.setText(_translate("admin", "Nhà tuyển dụng"))
        self.bt_listcongviec.setText(_translate("admin", "Công việc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin = QtWidgets.QMainWindow()
    ui = Ui_admin()
    ui.setupUi(admin)
    admin.show()
    sys.exit(app.exec())
