# Form implementation generated from reading ui file 'admin_ThongTinCongViec.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_chiTietCongViec(object):
    def setupUi(self, chiTietCongViec):
        chiTietCongViec.setObjectName("chiTietCongViec")
        chiTietCongViec.resize(527, 506)
        self.centralwidget = QtWidgets.QWidget(parent=chiTietCongViec)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 20, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 80, 491, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.li_TTCongViec_ntd = QtWidgets.QListView(parent=self.groupBox)
        self.li_TTCongViec_ntd.setGeometry(QtCore.QRect(20, 30, 451, 111))
        self.li_TTCongViec_ntd.setObjectName("li_TTCongViec_ntd")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 260, 491, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.table_dsCongViec.setGeometry(QtCore.QRect(20, 30, 451, 151))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(2)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_dsCongViec.setItem(0, 0, item)
        chiTietCongViec.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=chiTietCongViec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 527, 26))
        self.menubar.setObjectName("menubar")
        chiTietCongViec.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=chiTietCongViec)
        self.statusbar.setObjectName("statusbar")
        chiTietCongViec.setStatusBar(self.statusbar)

        self.retranslateUi(chiTietCongViec)
        QtCore.QMetaObject.connectSlotsByName(chiTietCongViec)
        self.loadThongTin()
        self.loadChiTiet()

    def retranslateUi(self, chiTietCongViec):
        _translate = QtCore.QCoreApplication.translate
        chiTietCongViec.setWindowTitle(_translate("chiTietCongViec", "Quản trị viên - Thông tin công việc"))
        self.label.setText(_translate("chiTietCongViec", "CHI TIẾT ỨNG TUYỂN CÔNG VIỆC"))
        self.groupBox.setTitle(_translate("chiTietCongViec", "I. THÔNG TIN CHUNG"))
        self.groupBox_2.setTitle(_translate("chiTietCongViec", "II. CHI TIẾT ỨNG TUYỂN CÔNG VIỆC"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("chiTietCongViec", "Mã chi tiết ứng tuyển"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("chiTietCongViec", "Tên người ứng tuyển"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)

    def loadThongTin(self):
        file = open("macongviec.txt", "r")
        macongviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT macongviec, tencongviec, mota, vitri, trinhdohocvan, "
                             "loaicongviec, chitieu, songuoiungtuyen, luong, tinhtrang FROM congviec "
                             "WHERE macongviec = %s", (macongviec,))
            cttt = mycursor.fetchall()

            thongtin = ["Mã công việc: ", "Tên công việc: ", "Mô tả: ", "Vị trí: ", "Trình độ học vấn",
                        "Loại công viêc: ", "Chỉ tiêu:", "Số người ứng tuyển: ", "Lương: ", "Tình trạng: "]

            if cttt:
                thongtin = [f"{thongtin[i]}{cttt[0][i]}" for i in range(len(thongtin))]

            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in thongtin:
                item = QtGui.QStandardItem(info)
                model.appendRow(item)
            self.li_TTCongViec_ntd.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")

    def loadChiTiet(self):
        file = open("macongviec.txt", "r")
        macongviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT machitietungtuyen, manguoitimviec FROM chitietungtuyen WHERE macongviec like %s", (macongviec, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    chiTietCongViec = QtWidgets.QMainWindow()
    ui = Ui_chiTietCongViec()
    ui.setupUi(chiTietCongViec)
    chiTietCongViec.show()
    sys.exit(app.exec())
