# Form implementation generated from reading ui file 'admin_QuanLyCongViec.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
import mysql.connector


class Ui_admin_QuanLyCongViec(object):
    def setupUi(self, admin_QuanLyCongViec):
        admin_QuanLyCongViec.setObjectName("admin_QuanLyCongViec")
        admin_QuanLyCongViec.resize(752, 506)
        self.centralwidget = QtWidgets.QWidget(parent=admin_QuanLyCongViec)
        self.centralwidget.setObjectName("centralwidget")
        self.te_macongviec = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_macongviec.setGeometry(QtCore.QRect(260, 350, 201, 31))
        self.te_macongviec.setObjectName("te_macongviec")
        self.te_tencongviec = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_tencongviec.setGeometry(QtCore.QRect(280, 80, 171, 31))
        self.te_tencongviec.setObjectName("te_tencongviec")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.bt_TimKiem_TimViec_dsCongViec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_TimKiem_TimViec_dsCongViec.setGeometry(QtCore.QRect(550, 70, 101, 41))
        self.bt_TimKiem_TimViec_dsCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_TimKiem_TimViec_dsCongViec.setObjectName("bt_TimKiem_TimViec_dsCongViec")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 350, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_dsCongViec.setGeometry(QtCore.QRect(40, 130, 661, 201))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(11)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_dsCongViec.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setItem(0, 2, item)
        self.bt_XemChiTiet = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_XemChiTiet.setGeometry(QtCore.QRect(110, 400, 151, 41))
        self.bt_XemChiTiet.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XemChiTiet.setObjectName("bt_XemChiTiet")
        self.bt_XoaCongViec_DSCongViec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_XoaCongViec_DSCongViec.setGeometry(QtCore.QRect(480, 400, 181, 41))
        self.bt_XoaCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XoaCongViec_DSCongViec.setObjectName("bt_XoaCongViec_DSCongViec")
        admin_QuanLyCongViec.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=admin_QuanLyCongViec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 26))
        self.menubar.setObjectName("menubar")
        admin_QuanLyCongViec.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=admin_QuanLyCongViec)
        self.statusbar.setObjectName("statusbar")
        admin_QuanLyCongViec.setStatusBar(self.statusbar)

        self.retranslateUi(admin_QuanLyCongViec)
        QtCore.QMetaObject.connectSlotsByName(admin_QuanLyCongViec)
        self.loadCongViec()
        self.bt_XemChiTiet.clicked.connect(self.chuyenDenThongTinCongViec)
        self.bt_XoaCongViec_DSCongViec.clicked.connect(self.xoaCongViec)

    def retranslateUi(self, admin_QuanLyCongViec):
        _translate = QtCore.QCoreApplication.translate
        admin_QuanLyCongViec.setWindowTitle(_translate("admin_QuanLyCongViec", "Quản trị viên - Quản Lý Công Việc"))
        self.label_2.setText(_translate("admin_QuanLyCongViec", "Tên công việc"))
        self.bt_TimKiem_TimViec_dsCongViec.setText(_translate("admin_QuanLyCongViec", "Tìm kiếm"))
        self.label_3.setText(_translate("admin_QuanLyCongViec", "Mã công việc"))
        self.label.setText(_translate("admin_QuanLyCongViec", "Danh sách công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("admin_QuanLyCongViec", "Mã công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("admin_QuanLyCongViec", "Nhà tuyển dụng"))
        item = self.table_dsCongViec.horizontalHeaderItem(2)
        item.setText(_translate("admin_QuanLyCongViec", "Tên công việc "))
        item = self.table_dsCongViec.horizontalHeaderItem(3)
        item.setText(_translate("admin_QuanLyCongViec", "Mô tả"))
        item = self.table_dsCongViec.horizontalHeaderItem(4)
        item.setText(_translate("admin_QuanLyCongViec", "Vị trí"))
        item = self.table_dsCongViec.horizontalHeaderItem(5)
        item.setText(_translate("admin_QuanLyCongViec", "Trình độ"))
        item = self.table_dsCongViec.horizontalHeaderItem(6)
        item.setText(_translate("admin_QuanLyCongViec", "Loại công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(7)
        item.setText(_translate("admin_QuanLyCongViec", "Chỉ tiêu"))
        item = self.table_dsCongViec.horizontalHeaderItem(8)
        item.setText(_translate("admin_QuanLyCongViec", "Số người ứng tuyển"))
        item = self.table_dsCongViec.horizontalHeaderItem(9)
        item.setText(_translate("admin_QuanLyCongViec", "Lương"))
        item = self.table_dsCongViec.horizontalHeaderItem(10)
        item.setText(_translate("admin_QuanLyCongViec", "Tình Trạng"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)
        self.bt_XemChiTiet.setText(_translate("admin_QuanLyCongViec", "Xem chi tiết"))
        self.bt_XoaCongViec_DSCongViec.setText(_translate("admin_QuanLyCongViec", "Xóa công việc"))

    def loadCongViec(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )

            mycursor = mydb.cursor()
            mycursor.execute("SELECT macongviec, manhatuyendung, tencongviec, mota, vitri, trinhdohocvan, "
                             "loaicongviec, chitieu, songuoiungtuyen, luong, tinhtrang FROM congviec")
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))

            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")

    def chuyenDenThongTinCongViec(self):
        macongviec = self.te_macongviec.text()
        file = open("macongviec.txt", "w")
        file.write(str(macongviec))
        file.close()
        subprocess.run(["python", "admin_ThongTinCongViec.py"])
        self.te_macongviec.setText("")

    def xoaCongViec(self):
        macongviec = self.te_macongviec.text()
        if macongviec == '':
            QtWidgets.QMessageBox.information(admin_QuanLyCongViec, "Thông báo", "Bạn không được để trống mã công việc.")
        else:
            try:
                mydb = mysql.connector.connect(
                    host="localhost",
                    user="root",
                    password="",
                    database="quanlygiaodichvieclam"
                )
                mycursor = mydb.cursor()
                sql = "DELETE FROM chitietungtuyen WHERE macongviec = %s"
                val = (macongviec,)
                mycursor.execute(sql, val)
                mydb.commit()

                sql = "DELETE FROM congviec WHERE macongviec = %s"
                val = (macongviec,)
                mycursor.execute(sql, val)
                mydb.commit()

                if mycursor.rowcount == 0:
                    QtWidgets.QMessageBox.information(admin_QuanLyCongViec, "Thông báo",
                                                      "Không tìm thấy mã công việc để xóa.")
                else:
                    QtWidgets.QMessageBox.information(admin_QuanLyCongViec, "Thông báo", "Xóa thành công.")
                    self.loadCongViec()
                mycursor.close()
                mydb.close()

                # Clear the input fields
                self.te_macongviec.setText("")
                self.te_tencongviec.setText("")
            except mysql.connector.Error as err:
                print("Error:", err)
                QtWidgets.QMessageBox.information(admin_QuanLyCongViec, "Thông báo", f"Có lỗi xảy ra khi xóa: {err}")
            except Exception as e:
                print("Error:", e)
                QtWidgets.QMessageBox.information(admin_QuanLyCongViec, "Thông báo", f"Có lỗi xảy ra khi xóa: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admin_QuanLyCongViec = QtWidgets.QMainWindow()
    ui = Ui_admin_QuanLyCongViec()
    ui.setupUi(admin_QuanLyCongViec)
    admin_QuanLyCongViec.show()
    sys.exit(app.exec())
