# Form implementation generated from reading ui file 'dangky.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
import mysql.connector


class Ui_dangky(object):
    def openhome(self):
        dangky.destroy()
        subprocess.run(["python", "trangchu.py"])

    def opentaohoso(self):
        subprocess.run(["python", "taohoso.py"])

    def setupUi(self, dangky):
        dangky.setObjectName("dangky")
        dangky.resize(920, 428)
        self.centralwidget = QtWidgets.QWidget(parent=dangky)
        self.centralwidget.setObjectName("centralwidget")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(460, 50, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.te_sdt_dangky = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_sdt_dangky.setGeometry(QtCore.QRect(170, 110, 241, 31))
        self.te_sdt_dangky.setObjectName("te_sdt_dangky")
        self.te_mail_dangky = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_mail_dangky.setGeometry(QtCore.QRect(170, 170, 241, 31))
        self.te_mail_dangky.setObjectName("te_mail_dangky")
        self.te_matkhau_dangky = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_matkhau_dangky.setGeometry(QtCore.QRect(630, 110, 241, 31))
        self.te_matkhau_dangky.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.te_matkhau_dangky.setObjectName("te_matkhau_dangky")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(460, 240, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.te_nhaplaimatkhau_dangky = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_nhaplaimatkhau_dangky.setGeometry(QtCore.QRect(630, 170, 241, 31))
        self.te_nhaplaimatkhau_dangky.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.te_nhaplaimatkhau_dangky.setObjectName("te_nhaplaimatkhau_dangky")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 240, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(460, 10, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.radio_nguoitimviec_dangky = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_nguoitimviec_dangky.setGeometry(QtCore.QRect(610, 240, 131, 20))
        self.radio_nguoitimviec_dangky.setObjectName("radio_nguoitimviec_dangky")
        self.label_mesage = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_mesage.setGeometry(QtCore.QRect(30, 280, 541, 16))
        self.label_mesage.setText("")
        self.label_mesage.setObjectName("label_mesage")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 180, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.te_thanhpho_dangky = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_thanhpho_dangky.setGeometry(QtCore.QRect(170, 230, 241, 31))
        self.te_thanhpho_dangky.setObjectName("te_thanhpho_dangky")
        self.radio_nhatuyendung_dangky = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_nhatuyendung_dangky.setGeometry(QtCore.QRect(750, 240, 131, 20))
        self.radio_nhatuyendung_dangky.setObjectName("radio_nhatuyendung_dangky")
        self.te_tendangnhap_dangky = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_tendangnhap_dangky.setGeometry(QtCore.QRect(630, 50, 241, 31))
        self.te_tendangnhap_dangky.setObjectName("te_tendangnhap_dangky")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(460, 116, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.bt_dangky_dangky = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_dangky_dangky.setGeometry(QtCore.QRect(290, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dangky_dangky.setFont(font)
        self.bt_dangky_dangky.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dangky_dangky.setObjectName("bt_dangky_dangky")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(460, 175, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.te_ten_dangky = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.te_ten_dangky.setGeometry(QtCore.QRect(170, 50, 241, 31))
        self.te_ten_dangky.setObjectName("te_ten_dangky")
        self.bt_dangNhap_dangky = QtWidgets.QPushButton(parent=dangky, clicked=lambda: self.openhome())
        self.bt_dangNhap_dangky.setGeometry(QtCore.QRect(480, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dangNhap_dangky.setFont(font)
        self.bt_dangNhap_dangky.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dangNhap_dangky.setObjectName("bt_dangNhap_dangky")
        dangky.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=dangky)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        dangky.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=dangky)
        self.statusbar.setObjectName("statusbar")
        dangky.setStatusBar(self.statusbar)

        self.retranslateUi(dangky)
        QtCore.QMetaObject.connectSlotsByName(dangky)

        self.bt_dangky_dangky.clicked.connect(self.rdangKy)

    def retranslateUi(self, dangky):
        _translate = QtCore.QCoreApplication.translate
        dangky.setWindowTitle(_translate("dangky", "Đăng ký"))
        self.label_7.setText(_translate("dangky", "Tên đăng nhập"))
        self.label_11.setText(_translate("dangky", "Bạn là"))
        self.label_4.setText(_translate("dangky", "Thành phố"))
        self.label_2.setText(_translate("dangky", "Tên"))
        self.label_5.setText(_translate("dangky", "Nhập vào các thông tin"))
        self.label_6.setText(_translate("dangky", "Tạo tài khoản"))
        self.radio_nguoitimviec_dangky.setText(_translate("dangky", "Người tìm việc"))
        self.label_3.setText(_translate("dangky", "Số điện thoại"))
        self.label_10.setText(_translate("dangky", "Mail"))
        self.radio_nhatuyendung_dangky.setText(_translate("dangky", "Nhà tuyển dụng"))
        self.label_8.setText(_translate("dangky", "Mật khẩu"))
        self.bt_dangky_dangky.setText(_translate("dangky", "Đăng ký"))
        self.label_9.setText(_translate("dangky", "Nhập lại mật khẩu"))
        self.bt_dangNhap_dangky.setText(_translate("dangky", "Đăng nhập"))

    def rdangKy(self):
        mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="quanlygiaodichvieclam"
        )

        mycursor = mydb.cursor()
        ten = self.te_ten_dangky.toPlainText()
        sdt = self.te_sdt_dangky.toPlainText()
        mail = self.te_mail_dangky.toPlainText()
        thanhpho = self.te_thanhpho_dangky.toPlainText()
        tendangnhap = self.te_tendangnhap_dangky.toPlainText()
        matkhau = self.te_matkhau_dangky.text()
        matkhau2 = self.te_nhaplaimatkhau_dangky.text()
        checkntv = self.radio_nguoitimviec_dangky.isChecked()
        checkntd = self.radio_nhatuyendung_dangky.isChecked()
        nguoitimviec = "0"
        nhatuyendung = "0"
        if checkntv:
            nguoitimviec = "1"
        if checkntd:
            nhatuyendung = "2"
        if (ten == '' or sdt == '' or mail == '' or thanhpho == '' or tendangnhap == '' or matkhau == '' or
                matkhau2 == '' or (nguoitimviec == "0" and nhatuyendung == "0")):
            QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Bạn không được để trống")
        else:
            if matkhau == matkhau2:
                try:
                    mycursor.execute("SELECT * FROM taikhoan WHERE tendangnhap = %s", (tendangnhap,))
                    result = mycursor.fetchall()
                    print("Query result:", result)
                    if result:
                        QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Tên đăng nhập đã tồn tại")
                    else:
                        mycursor.execute(
                            "INSERT INTO taikhoan (tendangnhap, matkhau, level) VALUES (%s, %s, %s)",
                            (tendangnhap, matkhau, nguoitimviec if nguoitimviec == "1" else nhatuyendung))
                        mydb.commit()

                        sql = "SELECT manguoidung FROM taikhoan WHERE tendangnhap = %s"
                        val = (tendangnhap,)
                        mycursor.execute(sql, val)
                        user_result = mycursor.fetchall()
                        print("User ID result:", user_result)
                        if user_result:
                            manguoidung = str(user_result[0][0])
                            if nguoitimviec == "1":
                                mycursor.execute(
                                    "INSERT INTO nguoitimviec (manguoidung, ten, sdt, mail, thanhpho) "
                                    "VALUES (%s, %s, %s, %s, %s)", (manguoidung, ten, sdt, mail, thanhpho))
                                mydb.commit()

                                sql = "SELECT manguoidung FROM taikhoan WHERE tendangnhap like %s AND matkhau like %s"
                                val = (tendangnhap, matkhau)
                                mycursor.execute(sql, val)
                                manguoidung = str(mycursor.fetchall())
                                manguoidung = manguoidung.replace("(", "").replace(",", "").replace(")", "").replace(
                                    "[", "").replace("]",
                                                     "")

                                sql = "SELECT manguoitimviec FROM nguoitimviec WHERE manguoidung like %s"
                                val = (manguoidung,)
                                mycursor.execute(sql, val)
                                manguoitimviec = str(mycursor.fetchall())
                                manguoitimviec = (manguoitimviec
                                                  .replace("(", "")
                                                  .replace(",", "")
                                                  .replace(")", "")
                                                  .replace("[", "")
                                                  .replace("]", ""))

                                file = open("manguoitimviec.txt", "w")
                                file.write(str(manguoitimviec))
                                file.close()

                                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                                  "Bạn đã đăng kí thành công, hãy tạo một hồ sơ!")
                                self.opentaohoso()
                            else:
                                mycursor.execute(
                                    "INSERT INTO nhatuyendung (manguoidung, ten, sdt, mail, thanhpho) "
                                    "VALUES (%s, %s, %s, %s, %s)", (manguoidung, ten, sdt, mail, thanhpho))
                                mydb.commit()
                                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Đăng kí thành công")
                        else:
                            QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                              "Đăng kí thất bại, không thể lấy ID người dùng.")
                except Exception as e:
                    print("Error:", e)
                    QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Có lỗi xảy ra khi đăng ký.")
            else:
                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Bạn nhập lại mật khẩu không đúng.")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    dangky = QtWidgets.QMainWindow()
    ui = Ui_dangky()
    ui.setupUi(dangky)
    dangky.show()
    sys.exit(app.exec())
