# Form implementation generated from reading ui file 'pheduyet.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 609)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 491, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.li_TTCongViec_ntd = QtWidgets.QListView(parent=self.groupBox)
        self.li_TTCongViec_ntd.setGeometry(QtCore.QRect(20, 30, 451, 111))
        self.li_TTCongViec_ntd.setObjectName("li_TTCongViec_ntd")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 250, 491, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.table_dsCongViec.setGeometry(QtCore.QRect(20, 30, 451, 151))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(2)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_dsCongViec.setItem(0, 0, item)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 450, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.te_machitietungtuyen = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_machitietungtuyen.setGeometry(QtCore.QRect(270, 450, 191, 31))
        self.te_machitietungtuyen.setObjectName("te_machitietungtuyen")
        self.bt_dongy = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_dongy.setGeometry(QtCore.QRect(60, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dongy.setFont(font)
        self.bt_dongy.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dongy.setObjectName("bt_dongy")
        self.bt_tuchoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_tuchoi.setGeometry(QtCore.QRect(340, 500, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_tuchoi.setFont(font)
        self.bt_tuchoi.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_tuchoi.setObjectName("bt_tuchoi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loadThongTin()
        self.loadChiTiet()
        self.bt_dongy.clicked.connect(self.chapNhan)
        self.bt_tuchoi.clicked.connect(self.tuChoi)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "I. THÔNG TIN CHUNG"))
        self.groupBox_2.setTitle(_translate("MainWindow", "II. CHI TIẾT ỨNG TUYỂN CÔNG VIỆC"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Chi tiết ứng tuyển"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Người ứng tuyển"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)
        self.label.setText(_translate("MainWindow", "CHI TIẾT ỨNG TUYỂN CÔNG VIỆC"))
        self.label_2.setText(_translate("MainWindow", "Mã chi tiết ứng tuyển"))
        self.bt_dongy.setText(_translate("MainWindow", "Phỏng vấn sau"))
        self.bt_tuchoi.setText(_translate("MainWindow", "Từ chối"))

    def loadThongTin(self):
        file = open("macongviec.txt", "r")
        macongviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT macongviec, tencongviec, mota, vitri, trinhdohocvan, "
                             "loaicongviec, chitieu, songuoiungtuyen, luong, tinhtrang FROM congviec "
                             "WHERE macongviec = %s", (macongviec,))
            cttt = mycursor.fetchall()

            thongtin = ["Mã công việc: ", "Tên công việc: ", "Mô tả: ", "Vị trí: ", "Trình độ học vấn",
                        "Loại công viêc: ", "Chỉ tiêu:", "Số người ứng tuyển: ", "Lương: ", "Tình trạng: "]

            if cttt:
                thongtin = [f"{thongtin[i]}{cttt[0][i]}" for i in range(len(thongtin))]

            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in thongtin:
                item = QtGui.QStandardItem(info)
                model.appendRow(item)
            self.li_TTCongViec_ntd.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")

    def loadChiTiet(self):
        file = open("macongviec.txt", "r")
        macongviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT machitietungtuyen, manguoitimviec FROM chitietungtuyen WHERE macongviec like %s", (macongviec, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")

    def tuChoi(self):
        machitietungtuyen = self.te_machitietungtuyen.text()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()

            # Truy vấn trạng thái
            mycursor.execute("SELECT trangthai FROM chitietungtuyen WHERE machitietungtuyen = %s", (machitietungtuyen,))
            result = mycursor.fetchone()

            if result and result[0] == "Chưa phê duyệt":
                # Sửa trạng thái chi tiết tuyển dụng
                mycursor.execute("UPDATE chitietungtuyen SET trangthai = %s WHERE machitietungtuyen = %s",
                                 ("Từ chối", machitietungtuyen))
                mydb.commit()

                # Thêm thông báo cho người tìm việc
                with open("manhatuyendung.txt", "r") as file:
                    manhatuyendung = file.read().strip()

                mycursor.execute("SELECT manguoitimviec FROM chitietungtuyen WHERE machitietungtuyen = %s",
                                 (machitietungtuyen,))
                manguoitimviec = mycursor.fetchone()[0]

                noidung = "Nhà tuyển dụng đã xem hồ sơ của bạn và từ chối tiếp nhận. Hãy cố gắng cho lần sau."
                mycursor.execute("INSERT INTO tbtontv (manhatuyendung, manguoitimviec, noidung) VALUES (%s, %s, %s)",
                                 (manhatuyendung, manguoitimviec, noidung))
                mydb.commit()

                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                  "Hoàn thành phê duyệt!")
            else:
                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                  "Bạn đã phê duyệt trước đó hoặc "
                                                  "không tồn tại mã chi tiết ứng tuyển này!")

            mycursor.close()
            mydb.close()
        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")

    def chapNhan(self):
        machitietungtuyen = self.te_machitietungtuyen.text()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()

            # Truy vấn trạng thái
            mycursor.execute("SELECT trangthai FROM chitietungtuyen WHERE machitietungtuyen = %s", (machitietungtuyen,))
            result = mycursor.fetchone()

            if result and result[0] == "Chưa phê duyệt":
                # Sửa trạng thái chi tiết tuyển dụng
                mycursor.execute("UPDATE chitietungtuyen SET trangthai = %s WHERE machitietungtuyen = %s",
                                 ("Chấp nhận", machitietungtuyen))
                mydb.commit()

                # Thêm thông báo cho người tìm việc
                with open("manhatuyendung.txt", "r") as file:
                    manhatuyendung = file.read().strip()

                mycursor.execute("SELECT manguoitimviec FROM chitietungtuyen WHERE machitietungtuyen = %s",
                                 (machitietungtuyen,))
                manguoitimviec = mycursor.fetchone()[0]

                noidung = ("Nhà tuyển dụng đã xem hồ sơ của bạn và chấp nhận, họ sẽ liên hệ với bạn về việc phỏng vấn "
                           "hoặc công việc liên quan, hãy chú ý điện thoại hoặc mail.")
                mycursor.execute("INSERT INTO tbtontv (manhatuyendung, manguoitimviec, noidung) VALUES (%s, %s, %s)",
                                 (manhatuyendung, manguoitimviec, noidung))
                mydb.commit()

                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                  "Hoàn thành phê duyệt! Hãy lên lịch phỏng vấn và liên hệ cho người tìm việc này.")
            else:
                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                                  "Bạn đã phê duyệt trước đó hoặc không tồn tại mã chi tiết ứng tuyển này!")

            mycursor.close()
            mydb.close()
        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
