# Form implementation generated from reading ui file 'taohoso.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="quanlygiaodichvieclam"
        )

mycursor = mydb.cursor()


class Ui_taoHoSo(object):
    def openhome(self):
        dangky.destroy()
        subprocess.run(["python", "trangchu.py"])

    def setupUi(self, taoHoSo):
        taoHoSo.setObjectName("taoHoSo")
        taoHoSo.resize(800, 720)
        self.centralwidget = QtWidgets.QWidget(parent=taoHoSo)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 130, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 290, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 370, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 450, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.te_kinhNghiemLamViec_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_kinhNghiemLamViec_ths.setGeometry(QtCore.QRect(260, 40, 491, 51))
        self.te_kinhNghiemLamViec_ths.setObjectName("te_kinhNghiemLamViec_ths")
        self.te_ThinhDoHocVan_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_ThinhDoHocVan_ths.setGeometry(QtCore.QRect(260, 120, 491, 51))
        self.te_ThinhDoHocVan_ths.setObjectName("te_ThinhDoHocVan_ths")
        self.te_HoatDong_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_HoatDong_ths.setGeometry(QtCore.QRect(260, 200, 491, 51))
        self.te_HoatDong_ths.setObjectName("te_HoatDong_ths")
        self.te_GiayKhen_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_GiayKhen_ths.setGeometry(QtCore.QRect(260, 280, 491, 51))
        self.te_GiayKhen_ths.setObjectName("te_GiayKhen_ths")
        self.te_DuAn_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_DuAn_ths.setGeometry(QtCore.QRect(260, 360, 491, 51))
        self.te_DuAn_ths.setObjectName("te_DuAn_ths")
        self.te_ChungChi_ths = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_ChungChi_ths.setGeometry(QtCore.QRect(260, 440, 491, 51))
        self.te_ChungChi_ths.setObjectName("te_ChungChi_ths")
        self.bt_TaoHoSo_ths = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_TaoHoSo_ths.setGeometry(QtCore.QRect(220, 590, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_TaoHoSo_ths.setFont(font)
        self.bt_TaoHoSo_ths.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_TaoHoSo_ths.setObjectName("bt_TaoHoSo_ths")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(50, 530, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.ra_Nam_ths = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.ra_Nam_ths.setGeometry(QtCore.QRect(260, 530, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ra_Nam_ths.setFont(font)
        self.ra_Nam_ths.setObjectName("ra_Nam_ths")
        self.ra_Nu_ths_2 = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.ra_Nu_ths_2.setGeometry(QtCore.QRect(530, 530, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ra_Nu_ths_2.setFont(font)
        self.ra_Nu_ths_2.setObjectName("ra_Nu_ths_2")
        self.bt_dangNhap_ths_2 = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.openhome())
        self.bt_dangNhap_ths_2.setGeometry(QtCore.QRect(410, 590, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dangNhap_ths_2.setFont(font)
        self.bt_dangNhap_ths_2.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dangNhap_ths_2.setObjectName("bt_dangNhap_ths_2")
        taoHoSo.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=taoHoSo)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        taoHoSo.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=taoHoSo)
        self.statusbar.setObjectName("statusbar")
        taoHoSo.setStatusBar(self.statusbar)

        self.retranslateUi(taoHoSo)
        QtCore.QMetaObject.connectSlotsByName(taoHoSo)

        self.bt_TaoHoSo_ths.clicked.connect(self.rtaohoso)

    def retranslateUi(self, taoHoSo):
        _translate = QtCore.QCoreApplication.translate
        taoHoSo.setWindowTitle(_translate("taoHoSo", "Tìm việc - Tạo hồ sơ"))
        self.label_2.setText(_translate("taoHoSo", "Kinh nghiệm làm việc"))
        self.label_3.setText(_translate("taoHoSo", "Trình độ học vấn"))
        self.label_4.setText(_translate("taoHoSo", "Hoạt động"))
        self.label_5.setText(_translate("taoHoSo", "Giấy khen"))
        self.label_6.setText(_translate("taoHoSo", "Dự án"))
        self.label_7.setText(_translate("taoHoSo", "Chứng chỉ"))
        self.bt_TaoHoSo_ths.setText(_translate("taoHoSo", "Tạo hồ sơ"))
        self.label_8.setText(_translate("taoHoSo", "Giới  tính"))
        self.ra_Nam_ths.setText(_translate("taoHoSo", "Nam"))
        self.ra_Nu_ths_2.setText(_translate("taoHoSo", "Nữ"))
        self.bt_dangNhap_ths_2.setText(_translate("taoHoSo", "Đăng nhập"))

    def rtaohoso(self):
        file = open("manguoitimviec.txt", "r")
        manguoitimviec = str(file.read())
        file.close()

        kn = self.te_kinhNghiemLamViec_ths.text()
        td = self.te_ThinhDoHocVan_ths.text()
        hd = self.te_HoatDong_ths.text()
        gk = self.te_GiayKhen_ths.text()
        da = self.te_DuAn_ths.text()
        cc = self.te_ChungChi_ths.text()
        checknam = self.ra_Nam_ths.isChecked()
        checknu = self.ra_Nu_ths_2.isChecked()

        if checknam:
            gioitinh = "Nam"
        else:
            gioitinh = "Nu"
        if checknam == False and checknu == False:
            QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Bạn không được để giới tính")
        else:
            try:
                mycursor.execute("INSERT INTO hoso "
                                 "(manguoitimviec, kinhnghiemlamviec, trinhdohocvan, hoatdong, giaykhen, duan, chungchi, gioitinh) "
                                 "VALUES (%s, %s, %s, %s, %s, %s, %s, %s)",
                                 (manguoitimviec, kn, td, hd, gk, da, cc, gioitinh))
                mydb.commit()
                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Hồ sơ của bạn đã hoàn tất")
            except Exception as e:
                print("Error:", e)
                QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo", "Có lỗi xảy ra khi tạo tài koản.")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    taoHoSo = QtWidgets.QMainWindow()
    ui = Ui_taoHoSo()
    ui.setupUi(taoHoSo)
    taoHoSo.show()
    sys.exit(app.exec())
