# Form implementation generated from reading ui file 'thongbao.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_thongbao(object):
    def setupUi(self, thongbao):
        thongbao.setObjectName("thongbao")
        thongbao.resize(531, 379)
        self.centralwidget = QtWidgets.QWidget(parent=thongbao)
        self.centralwidget.setObjectName("centralwidget")
        self.listThongBao = QtWidgets.QListView(parent=self.centralwidget)
        self.listThongBao.setGeometry(QtCore.QRect(60, 60, 411, 161))
        self.listThongBao.setObjectName("listThongBao")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 10, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 230, 341, 20))
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 250, 241, 21))
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.bt_xoaThongBao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_xoaThongBao.setGeometry(QtCore.QRect(170, 280, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_xoaThongBao.setFont(font)
        self.bt_xoaThongBao.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_xoaThongBao.setObjectName("bt_xoaThongBao")
        thongbao.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=thongbao)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 531, 26))
        self.menubar.setObjectName("menubar")
        thongbao.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=thongbao)
        self.statusbar.setObjectName("statusbar")
        thongbao.setStatusBar(self.statusbar)

        self.retranslateUi(thongbao)
        QtCore.QMetaObject.connectSlotsByName(thongbao)
        self.bt_xoaThongBao.clicked.connect(self.doiCapNhat)
        self.loadThongTin()

    def retranslateUi(self, thongbao):
        _translate = QtCore.QCoreApplication.translate
        thongbao.setWindowTitle(_translate("thongbao", "Thông báo"))
        self.label.setText(_translate("thongbao", "Danh sách thông báo"))
        self.label_2.setText(_translate("thongbao", "* Khi bạn click vào thông báo và click vào nút xóa này,"))
        self.label_3.setText(_translate("thongbao", " thông báo bạn đã chọn sẽ bị xóa."))
        self.bt_xoaThongBao.setText(_translate("thongbao", "Xóa thông báo"))

    def doiCapNhat(self):
        QtWidgets.QMessageBox.information(self.centralwidget, "Thông báo",
                                          "Chức năng này tạm thời chưa dùng được, hãy đợi ở bản cập nhật sau.")

    def loadThongTin(self):
        file = open("manguoidung.txt", "r")
        manguoidung = str(file.read().strip())
        file.close()
        file = open("manguoitimviec.txt", "r")
        manguoitimviec = str(file.read().strip())
        file.close()
        file = open("manhatuyendung.txt", "r")
        manhatuyendung = str(file.read().strip())
        file.close()

        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT level FROM taikhoan WHERE manguoidung = %s", (manguoidung,))
            level = (str(mycursor.fetchall())
                     .replace("(", "")
                     .replace(",", "")
                     .replace(")", "")
                     .replace("[", "")
                     .replace("]", ""))
            if level == "1":
                mycursor.execute("SELECT noidung FROM tbtontv WHERE manguoitimviec = %s", (manguoitimviec,))
            else:
                mycursor.execute("SELECT noidung FROM tbtontd WHERE manhatuyendung = %s", (manhatuyendung,))

            data = mycursor.fetchall()
            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in data:
                item = QtGui.QStandardItem(str(info)
                                           .replace("(", "")
                                           .replace(")", "")
                                           .replace(",", "")
                                           .replace("'", ""))
                model.appendRow(item)
            self.listThongBao.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thongbao = QtWidgets.QMainWindow()
    ui = Ui_thongbao()
    ui.setupUi(thongbao)
    thongbao.show()
    sys.exit(app.exec())
