# Form implementation generated from reading ui file 'timviec_DanhSachNhaTuyenDung.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
import mysql.connector


class Ui_timviec_DSNhatuyendung(object):
    def setupUi(self, timviec_DSNhatuyendung):
        timviec_DSNhatuyendung.setObjectName("timviec_DSNhatuyendung")
        timviec_DSNhatuyendung.resize(702, 475)
        self.centralwidget = QtWidgets.QWidget(parent=timviec_DSNhatuyendung)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_XemChiTietCongViec_DSNhaTuyenDung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_XemChiTietCongViec_DSNhaTuyenDung.setGeometry(QtCore.QRect(510, 360, 161, 41))
        self.bt_XemChiTietCongViec_DSNhaTuyenDung.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XemChiTietCongViec_DSNhaTuyenDung.setObjectName("bt_XemChiTietCongViec_DSNhaTuyenDung")
        self.te_TimKiemTheoTenNTD = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_TimKiemTheoTenNTD.setGeometry(QtCore.QRect(240, 90, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.te_TimKiemTheoTenNTD.setFont(font)
        self.te_TimKiemTheoTenNTD.setObjectName("te_TimKiemTheoTenNTD")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_dsCongViec.setGeometry(QtCore.QRect(80, 160, 531, 171))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(5)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setItem(0, 1, item)
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 370, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 181, 31))
        self.label_2.setObjectName("label_2")
        self.te_MaNhaTuyenDung_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_MaNhaTuyenDung_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(250, 370, 201, 31))
        self.te_MaNhaTuyenDung_TuyenDung_DSCongViec.setObjectName("te_MaNhaTuyenDung_TuyenDung_DSCongViec")
        self.bt_TimKiem_TimViec_dsNhaTuyenDung = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_TimKiem_TimViec_dsNhaTuyenDung.setGeometry(QtCore.QRect(570, 90, 101, 41))
        self.bt_TimKiem_TimViec_dsNhaTuyenDung.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_TimKiem_TimViec_dsNhaTuyenDung.setObjectName("bt_TimKiem_TimViec_dsNhaTuyenDung")
        timviec_DSNhatuyendung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=timviec_DSNhatuyendung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 702, 26))
        self.menubar.setObjectName("menubar")
        timviec_DSNhatuyendung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=timviec_DSNhatuyendung)
        self.statusbar.setObjectName("statusbar")
        timviec_DSNhatuyendung.setStatusBar(self.statusbar)

        self.retranslateUi(timviec_DSNhatuyendung)
        QtCore.QMetaObject.connectSlotsByName(timviec_DSNhatuyendung)
        self.bt_TimKiem_TimViec_dsNhaTuyenDung.clicked.connect(self.timNguoiTimViecTheoTen)
        self.bt_XemChiTietCongViec_DSNhaTuyenDung.clicked.connect(self.chuyenDenThongTinNTD)
        self.loaddata()

    def retranslateUi(self, timviec_DSNhatuyendung):
        _translate = QtCore.QCoreApplication.translate
        timviec_DSNhatuyendung.setWindowTitle(_translate("timviec_DSNhatuyendung", "Tìm việc - Danh sách nhà tuyển dụng"))
        self.bt_XemChiTietCongViec_DSNhaTuyenDung.setText(_translate("timviec_DSNhatuyendung", "Xem chi tiết "))
        self.label.setText(_translate("timviec_DSNhatuyendung", "<html><head/><body><p><span style=\" font-size:18pt;\">Nhà tuyển dụng</span></p></body></html>"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("timviec_DSNhatuyendung", "Mã"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("timviec_DSNhatuyendung", "Tên"))
        item = self.table_dsCongViec.horizontalHeaderItem(2)
        item.setText(_translate("timviec_DSNhatuyendung", "Số điện thoại"))
        item = self.table_dsCongViec.horizontalHeaderItem(3)
        item.setText(_translate("timviec_DSNhatuyendung", "Mail"))
        item = self.table_dsCongViec.horizontalHeaderItem(4)
        item.setText(_translate("timviec_DSNhatuyendung", "Thành phố"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("timviec_DSNhatuyendung", "Mã nhà tuyển dụng"))
        self.label_2.setText(_translate("timviec_DSNhatuyendung", "<html><head/><body><p><span style=\" font-size:12pt;\">Tên nhà tuyển dụng</span></p></body></html>"))
        self.bt_TimKiem_TimViec_dsNhaTuyenDung.setText(_translate("timviec_DSNhatuyendung", "Tìm kiếm"))

    def timNguoiTimViecTheoTen(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            tennhatuyendung = self.te_TimKiemTheoTenNTD.text()
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manhatuyendung, ten, sdt, mail, thanhpho FROM nhatuyendung WHERE ten like %s",
                             (tennhatuyendung, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            self.te_TimKiemTheoTenNTD.setText("")
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
            self.te_TimKiemTheoTenNTD.setText("")
        except Exception as e:
            print(f"Error: {e}")
            self.te_TimKiemTheoTenNTD.setText("")

    def loaddata(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manhatuyendung, ten, sdt, mail, thanhpho FROM nhatuyendung")
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))

            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")

    def chuyenDenThongTinNTD(self):
        manhatuyendung = self.te_MaNhaTuyenDung_TuyenDung_DSCongViec.text()
        file = open("manhatuyendung.txt", "w")
        file.write(str(manhatuyendung))
        file.close()
        subprocess.run(["python", "timviec_ThongTinNhaTuyenDung.py"])
        self.te_MaNhaTuyenDung_TuyenDung_DSCongViec.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timviec_DSNhatuyendung = QtWidgets.QMainWindow()
    ui = Ui_timviec_DSNhatuyendung()
    ui.setupUi(timviec_DSNhatuyendung)
    timviec_DSNhatuyendung.show()
    sys.exit(app.exec())
