# Form implementation generated from reading ui file 'timviec_ThongTinNhaTuyenDung.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_timvie_ThongTinNhaTuyenDung(object):
    def setupUi(self, timvie_ThongTinNhaTuyenDung):
        timvie_ThongTinNhaTuyenDung.setObjectName("timvie_ThongTinNhaTuyenDung")
        timvie_ThongTinNhaTuyenDung.resize(754, 501)
        self.centralwidget = QtWidgets.QWidget(parent=timvie_ThongTinNhaTuyenDung)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 70, 711, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.li_TTNhaTuyenDung_TimViec = QtWidgets.QListView(parent=self.groupBox)
        self.li_TTNhaTuyenDung_TimViec.setGeometry(QtCore.QRect(20, 30, 671, 111))
        self.li_TTNhaTuyenDung_TimViec.setObjectName("li_TTNhaTuyenDung_TimViec")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 250, 711, 191))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.groupBox_2)
        self.table_dsCongViec.setGeometry(QtCore.QRect(20, 30, 661, 151))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(11)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_dsCongViec.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setItem(0, 2, item)
        timvie_ThongTinNhaTuyenDung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=timvie_ThongTinNhaTuyenDung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 754, 26))
        self.menubar.setObjectName("menubar")
        timvie_ThongTinNhaTuyenDung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=timvie_ThongTinNhaTuyenDung)
        self.statusbar.setObjectName("statusbar")
        timvie_ThongTinNhaTuyenDung.setStatusBar(self.statusbar)

        self.retranslateUi(timvie_ThongTinNhaTuyenDung)
        QtCore.QMetaObject.connectSlotsByName(timvie_ThongTinNhaTuyenDung)
        self.loadThongTin()
        self.loadCongViec()

    def retranslateUi(self, timvie_ThongTinNhaTuyenDung):
        _translate = QtCore.QCoreApplication.translate
        timvie_ThongTinNhaTuyenDung.setWindowTitle(_translate("timvie_ThongTinNhaTuyenDung", "Tìm việc - Thông tin nhà tuyển dụng"))
        self.label.setText(_translate("timvie_ThongTinNhaTuyenDung", "THÔNG TIN NHÀ TUYỂN DỤNG"))
        self.groupBox.setTitle(_translate("timvie_ThongTinNhaTuyenDung", "I. THÔNG TIN CHUNG"))
        self.groupBox_2.setTitle(_translate("timvie_ThongTinNhaTuyenDung", "II. CÁC CÔNG VIỆC"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Mã công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Nhà tuyển dụng"))
        item = self.table_dsCongViec.horizontalHeaderItem(2)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Tên công việc "))
        item = self.table_dsCongViec.horizontalHeaderItem(3)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Mô tả"))
        item = self.table_dsCongViec.horizontalHeaderItem(4)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Vị trí"))
        item = self.table_dsCongViec.horizontalHeaderItem(5)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Trình độ"))
        item = self.table_dsCongViec.horizontalHeaderItem(6)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Loại công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(7)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Chỉ tiêu"))
        item = self.table_dsCongViec.horizontalHeaderItem(8)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Số người ứng tuyển"))
        item = self.table_dsCongViec.horizontalHeaderItem(9)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Lương"))
        item = self.table_dsCongViec.horizontalHeaderItem(10)
        item.setText(_translate("timvie_ThongTinNhaTuyenDung", "Tình Trạng"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)

    def loadThongTin(self):
        file = open("manhatuyendung.txt", "r")
        manhatuyendung = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manhatuyendung, ten, sdt, mail, thanhpho FROM nhatuyendung "
                             "WHERE manhatuyendung = %s", (manhatuyendung,))
            cttt = mycursor.fetchall()

            thongtin = ["Mã nhà tuyển dụng: ", "Tên: ", "Số điện thoại: ", "Mail: ", "Thành phố: "]

            if cttt:
                thongtin = [f"{thongtin[i]}{cttt[0][i]}" for i in range(len(thongtin))]

            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in thongtin:
                item = QtGui.QStandardItem(info)
                model.appendRow(item)
            self.li_TTNhaTuyenDung_TimViec.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")

    def loadCongViec(self):
        file = open("manhatuyendung.txt", "r")
        manhatuyendung = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM congviec WHERE manhatuyendung like %s", (manhatuyendung, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    timvie_ThongTinNhaTuyenDung = QtWidgets.QMainWindow()
    ui = Ui_timvie_ThongTinNhaTuyenDung()
    ui.setupUi(timvie_ThongTinNhaTuyenDung)
    timvie_ThongTinNhaTuyenDung.show()
    sys.exit(app.exec())
