# Form implementation generated from reading ui file 'trangchu.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess

from PyQt6 import QtCore, QtGui, QtWidgets
from taohoso import Ui_taoHoSo
from dangky import Ui_dangky
from tkinter import messagebox
import mysql.connector


mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="quanlygiaodichvieclam"
        )

mycursor = mydb.cursor()


class Ui_MainWindow(object):
    def chuyenDenTuyenDung(self):
        MainWindow.destroy()
        subprocess.run(["python", "tuyendung.py"])

    def chuyenDenTaoHoSo(self):
        subprocess.run(["python", "taohoso.py"])

    def chuyenDenMenuTuyenDung(self):
        MainWindow.destroy()
        subprocess.run(["python", "tuyendung.py"])

    def chuyenDenMenuTimViec(self):
        MainWindow.destroy()
        subprocess.run(["python", "timviec.py"])

    def chuyenDenDangKy(self):
        subprocess.run(["python", "dangky.py"])

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(648, 430)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(400, 280, 161, 16))
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 40, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(360, 130, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.bt_dangnhap = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_dangnhap.setGeometry(QtCore.QRect(420, 210, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dangnhap.setFont(font)
        self.bt_dangnhap.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dangnhap.setObjectName("bt_dangnhap")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, -30, 321, 421))
        self.groupBox.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(80, 110, 131, 51))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(80, 150, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(80, 190, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_4.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 260, 101, 20))
        self.label_7.setObjectName("label_7")
        self.bt_dangky = QtWidgets.QPushButton(parent=self.centralwidget, clicked=lambda: self.chuyenDenDangKy())
        self.bt_dangky.setGeometry(QtCore.QRect(420, 310, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_dangky.setFont(font)
        self.bt_dangky.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_dangky.setObjectName("bt_dangky")
        self.te_tendangnhap = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_tendangnhap.setGeometry(QtCore.QRect(360, 71, 241, 31))
        self.te_tendangnhap.setObjectName("te_tendangnhap")
        self.te_matkhau = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_matkhau.setGeometry(QtCore.QRect(360, 161, 241, 31))
        self.te_matkhau.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.te_matkhau.setObjectName("te_matkhau")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 648, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.bt_dangnhap.clicked.connect(self.rdangnhap)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "nếu bạn chưa có tài khoản"))
        self.label_5.setText(_translate("MainWindow", "Tên đăng nhập"))
        self.label_6.setText(_translate("MainWindow", "Mật khẩu"))
        self.bt_dangnhap.setText(_translate("MainWindow", "Đăng nhập"))
        self.label.setText(_translate("MainWindow", "Công ty "))
        self.label_2.setText(_translate("MainWindow", "giao dịch, "))
        self.label_3.setText(_translate("MainWindow", "môi giới"))
        self.label_4.setText(_translate("MainWindow", "viêc làm"))
        self.label_7.setText(_translate("MainWindow", "Click vào đăng ký"))
        self.bt_dangky.setText(_translate("MainWindow", "Đăng ký"))

    def rdangnhap(self):
        username = self.te_tendangnhap.text()
        password = self.te_matkhau.text()
        if username == '' or password == '':
            messagebox.showinfo("Login output", "Bạn không được bỏ trống")
        else:
            # lưu mã nguời dùng vào một file txt dùng sau này
            sql = "SELECT manguoidung FROM taikhoan WHERE tendangnhap like %s AND matkhau like %s"
            val = (username, password)
            mycursor.execute(sql, val)
            manguoidung = (str(mycursor.fetchall())
                           .replace("(", "")
                           .replace(",", "")
                           .replace(")", "")
                           .replace("[", "")
                           .replace("]", ""))
            file = open("manguoidung.txt", "w")
            file.write(str(manguoidung))
            file.close()

            sql = "SELECT manguoidung FROM taikhoan WHERE tendangnhap like %s AND matkhau like %s"
            val = (username, password)
            mycursor.execute(sql, val)
            b = bool(mycursor.fetchall())
            if b:
                sql = "SELECT level FROM taikhoan WHERE tendangnhap like %s AND matkhau like %s"
                val = (username, password)
                mycursor.execute(sql, val)
                z = str(mycursor.fetchall())
                z = z.replace("(", "").replace(",", "").replace(")", "").replace("[", "").replace("]", "")
                if z == '1' or z == '2':
                    if z == '1':
                        sql = "SELECT manguoitimviec FROM nguoitimviec WHERE manguoidung like %s"
                        val = (manguoidung,)
                        mycursor.execute(sql, val)
                        manguoitimviec = str(mycursor.fetchall())
                        manguoitimviec = manguoitimviec.replace("(", "").replace(",", "").replace(")", "").replace(
                            "[", "").replace("]",
                                             "")

                        file = open("manguoitimviec.txt", "w")
                        file.write(str(manguoitimviec))
                        file.close()

                        sql = "SELECT manguoitimviec FROM hoso WHERE manguoitimviec like %s"
                        val = (manguoitimviec,)
                        mycursor.execute(sql, val)
                        manguoitimviec = bool(mycursor.fetchall())
                        if manguoitimviec:
                            messagebox.showinfo("Message",
                                                "Đăng nhập thành công!")
                            self.chuyenDenMenuTimViec()
                            self.te_tendangnhap.setText("")
                            self.te_matkhau.setText("")
                        else:
                            messagebox.showinfo("Message",
                                                "Bạn chưa có hồ sơ, hãy tạo hồ sơ để tiếp tục sử dụng dịch vụ")
                            self.chuyenDenTaoHoSo()
                    if z == '2':
                        sql = "SELECT manhatuyendung FROM nhatuyendung WHERE manguoidung like %s"
                        val = (manguoidung,)
                        mycursor.execute(sql, val)
                        manhatuyendung = str(mycursor.fetchall())
                        manhatuyendung = manhatuyendung.replace("(", "").replace(",", "").replace(")", "").replace(
                            "[", "").replace("]",
                                             "")
                        file = open("manhatuyendung.txt", "w")
                        file.write(str(manhatuyendung))
                        file.close()
                        messagebox.showinfo("Message",
                                            "Đăng nhập thành công!")
                        self.te_tendangnhap.setText("")
                        self.te_matkhau.setText("")
                        self.chuyenDenTuyenDung()
                else:
                    MainWindow.destroy()
                    subprocess.run(["python", "admin.py"])
            else:
                messagebox.showinfo("Login output",
                                    "Có thể bạn đã nhập sai, hãy nhập lại. Nếu bạn chưa có tài khoản, "
                                    "hãy click vào Đăng ký để tạo một tài khoản")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
