# Form implementation generated from reading ui file 'tuyendung_QuanLyCongViec.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
import mysql.connector
mydb = mysql.connector.connect(
            host="localhost",
            user="root",
            password="",
            database="quanlygiaodichvieclam"
        )

mycursor = mydb.cursor()


class Ui_TuyenDung_DSCongViec(object):
    def setupUi(self, TuyenDung_DSCongViec):
        TuyenDung_DSCongViec.setObjectName("TuyenDung_DSCongViec")
        TuyenDung_DSCongViec.resize(931, 767)
        self.label = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label.setGeometry(QtCore.QRect(290, 0, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.te_TimKiemTheoTenCV = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_TimKiemTheoTenCV.setGeometry(QtCore.QRect(260, 70, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.te_TimKiemTheoTenCV.setFont(font)
        self.te_TimKiemTheoTenCV.setObjectName("te_TimKiemTheoTenCV")
        self.label_2 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_2.setGeometry(QtCore.QRect(70, 80, 141, 31))
        self.label_2.setObjectName("label_2")
        self.bt_TimKiem_TuyenDung_dsCongViec = QtWidgets.QPushButton(parent=TuyenDung_DSCongViec)
        self.bt_TimKiem_TuyenDung_dsCongViec.setGeometry(QtCore.QRect(720, 70, 101, 41))
        self.bt_TimKiem_TuyenDung_dsCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_TimKiem_TuyenDung_dsCongViec.setObjectName("bt_TimKiem_TuyenDung_dsCongViec")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=TuyenDung_DSCongViec)
        self.table_dsCongViec.setGeometry(QtCore.QRect(40, 150, 851, 171))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(11)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.table_dsCongViec.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setItem(0, 3, item)
        self.bt_ThemCongViec_DSCongViec = QtWidgets.QPushButton(parent=TuyenDung_DSCongViec)
        self.bt_ThemCongViec_DSCongViec.setGeometry(QtCore.QRect(90, 690, 101, 41))
        self.bt_ThemCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_ThemCongViec_DSCongViec.setObjectName("bt_ThemCongViec_DSCongViec")
        self.bt_SuaCongViec_DSCongViec = QtWidgets.QPushButton(parent=TuyenDung_DSCongViec)
        self.bt_SuaCongViec_DSCongViec.setGeometry(QtCore.QRect(300, 690, 101, 41))
        self.bt_SuaCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_SuaCongViec_DSCongViec.setObjectName("bt_SuaCongViec_DSCongViec")
        self.bt_XoaCongViec_DSCongViec = QtWidgets.QPushButton(parent=TuyenDung_DSCongViec)
        self.bt_XoaCongViec_DSCongViec.setGeometry(QtCore.QRect(480, 690, 101, 41))
        self.bt_XoaCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XoaCongViec_DSCongViec.setObjectName("bt_XoaCongViec_DSCongViec")
        self.bt_XemChiTietCongViec_DSCongViec = QtWidgets.QPushButton(parent=TuyenDung_DSCongViec)
        self.bt_XemChiTietCongViec_DSCongViec.setGeometry(QtCore.QRect(680, 690, 141, 41))
        self.bt_XemChiTietCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XemChiTietCongViec_DSCongViec.setObjectName("bt_XemChiTietCongViec_DSCongViec")
        self.label_3 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_3.setGeometry(QtCore.QRect(50, 420, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_4.setGeometry(QtCore.QRect(50, 470, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_5.setGeometry(QtCore.QRect(50, 530, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_6.setGeometry(QtCore.QRect(50, 590, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_7.setGeometry(QtCore.QRect(500, 350, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_8.setGeometry(QtCore.QRect(500, 410, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_9.setGeometry(QtCore.QRect(500, 470, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_10.setGeometry(QtCore.QRect(500, 530, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.te_TenCongViec_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_TenCongViec_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(230, 421, 201, 31))
        self.te_TenCongViec_TuyenDung_DSCongViec.setObjectName("te_TenCongViec_TuyenDung_DSCongViec")
        self.te_MoTa_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_MoTa_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(230, 480, 201, 31))
        self.te_MoTa_TuyenDung_DSCongViec.setObjectName("te_MoTa_TuyenDung_DSCongViec")
        self.te_ViTri_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_ViTri_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(230, 540, 201, 31))
        self.te_ViTri_TuyenDung_DSCongViec.setObjectName("te_ViTri_TuyenDung_DSCongViec")
        self.Te_TrinhDo_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.Te_TrinhDo_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(230, 600, 201, 31))
        self.Te_TrinhDo_TuyenDung_DSCongViec.setObjectName("Te_TrinhDo_TuyenDung_DSCongViec")
        self.te_LoaiCongViec_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_LoaiCongViec_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(680, 360, 201, 31))
        self.te_LoaiCongViec_TuyenDung_DSCongViec.setObjectName("te_LoaiCongViec_TuyenDung_DSCongViec")
        self.te_ChiTieu_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_ChiTieu_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(680, 420, 201, 31))
        self.te_ChiTieu_TuyenDung_DSCongViec.setObjectName("te_ChiTieu_TuyenDung_DSCongViec")
        self.te_Luong_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_Luong_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(680, 480, 201, 31))
        self.te_Luong_TuyenDung_DSCongViec.setObjectName("te_Luong_TuyenDung_DSCongViec")
        self.te_TinhTrang_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_TinhTrang_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(680, 540, 201, 31))
        self.te_TinhTrang_TuyenDung_DSCongViec.setObjectName("te_TinhTrang_TuyenDung_DSCongViec")
        self.te_MaCongViec_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=TuyenDung_DSCongViec)
        self.te_MaCongViec_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(230, 360, 201, 31))
        self.te_MaCongViec_TuyenDung_DSCongViec.setObjectName("te_MaCongViec_TuyenDung_DSCongViec")
        self.label_11 = QtWidgets.QLabel(parent=TuyenDung_DSCongViec)
        self.label_11.setGeometry(QtCore.QRect(50, 360, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")

        self.retranslateUi(TuyenDung_DSCongViec)
        QtCore.QMetaObject.connectSlotsByName(TuyenDung_DSCongViec)

        self.bt_ThemCongViec_DSCongViec.clicked.connect(self.themCongViec)
        self.bt_XoaCongViec_DSCongViec.clicked.connect(self.xoaCongViec)
        self.bt_SuaCongViec_DSCongViec.clicked.connect(self.suaCongViec)
        self.bt_TimKiem_TuyenDung_dsCongViec.clicked.connect(self.timCongViecTheoTen)
        self.bt_XemChiTietCongViec_DSCongViec.clicked.connect(self.chuyenDenPheDuyet)
        self.loaddata()

    def retranslateUi(self, TuyenDung_DSCongViec):
        _translate = QtCore.QCoreApplication.translate
        TuyenDung_DSCongViec.setWindowTitle(_translate("TuyenDung_DSCongViec", "Tuyển Dụng - Danh Sách Công Việc"))
        self.label.setText(_translate("TuyenDung_DSCongViec", "<html><head/><body><p><span style=\" font-size:18pt;\">Quản lý công việc </span></p></body></html>"))
        self.label_2.setText(_translate("TuyenDung_DSCongViec", "<html><head/><body><p><span style=\" font-size:12pt;\">Tên công việc</span></p></body></html>"))
        self.bt_TimKiem_TuyenDung_dsCongViec.setText(_translate("TuyenDung_DSCongViec", "Tìm kiếm"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("TuyenDung_DSCongViec", "Mã công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("TuyenDung_DSCongViec", "Nhà tuyển dụng"))
        item = self.table_dsCongViec.horizontalHeaderItem(2)
        item.setText(_translate("TuyenDung_DSCongViec", "Trình độ"))
        item = self.table_dsCongViec.horizontalHeaderItem(3)
        item.setText(_translate("TuyenDung_DSCongViec", "Tên công việc "))
        item = self.table_dsCongViec.horizontalHeaderItem(4)
        item.setText(_translate("TuyenDung_DSCongViec", "Loại công việc"))
        item = self.table_dsCongViec.horizontalHeaderItem(5)
        item.setText(_translate("TuyenDung_DSCongViec", "Chỉ tiêu"))
        item = self.table_dsCongViec.horizontalHeaderItem(6)
        item.setText(_translate("TuyenDung_DSCongViec", "Số người ứng tuyển"))
        item = self.table_dsCongViec.horizontalHeaderItem(7)
        item.setText(_translate("TuyenDung_DSCongViec", "Mô tả"))
        item = self.table_dsCongViec.horizontalHeaderItem(8)
        item.setText(_translate("TuyenDung_DSCongViec", "Vị trí"))
        item = self.table_dsCongViec.horizontalHeaderItem(9)
        item.setText(_translate("TuyenDung_DSCongViec", "Tình Trạng"))
        item = self.table_dsCongViec.horizontalHeaderItem(10)
        item.setText(_translate("TuyenDung_DSCongViec", "Lương"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)
        self.bt_ThemCongViec_DSCongViec.setText(_translate("TuyenDung_DSCongViec", "Thêm"))
        self.bt_SuaCongViec_DSCongViec.setText(_translate("TuyenDung_DSCongViec", "Sửa"))
        self.bt_XoaCongViec_DSCongViec.setText(_translate("TuyenDung_DSCongViec", "Xóa"))
        self.bt_XemChiTietCongViec_DSCongViec.setText(_translate("TuyenDung_DSCongViec", "Xem chi tiết"))
        self.label_3.setText(_translate("TuyenDung_DSCongViec", "Tên công việc"))
        self.label_4.setText(_translate("TuyenDung_DSCongViec", "Mô tả"))
        self.label_5.setText(_translate("TuyenDung_DSCongViec", "Vị trí tuyển dụng"))
        self.label_6.setText(_translate("TuyenDung_DSCongViec", "Trình độ"))
        self.label_7.setText(_translate("TuyenDung_DSCongViec", "Loại công việc"))
        self.label_8.setText(_translate("TuyenDung_DSCongViec", "Chỉ tiêu"))
        self.label_9.setText(_translate("TuyenDung_DSCongViec", "Lương / tháng"))
        self.label_10.setText(_translate("TuyenDung_DSCongViec", "Tình trạng"))
        self.label_11.setText(_translate("TuyenDung_DSCongViec", "Mã công việc"))

    def timCongViecTheoTen(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            tencongviec = self.te_TimKiemTheoTenCV.text()
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM congviec WHERE tencongviec like %s", (tencongviec, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            self.te_TimKiemTheoTenCV.setText("")
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
            self.te_TimKiemTheoTenCV.setText("")
        except Exception as e:
            print(f"Error: {e}")
            self.te_TimKiemTheoTenCV.setText("")

    def themCongViec(self):
        tencongviec = self.te_TenCongViec_TuyenDung_DSCongViec.text()
        mota = self.te_MoTa_TuyenDung_DSCongViec.text()
        vitrituyendung = self.te_ViTri_TuyenDung_DSCongViec.text()
        trinhdo = self.Te_TrinhDo_TuyenDung_DSCongViec.text()
        loaicongviec = self.te_LoaiCongViec_TuyenDung_DSCongViec.text()
        chitieu = self.te_ChiTieu_TuyenDung_DSCongViec.text()
        luong = self.te_Luong_TuyenDung_DSCongViec.text()
        tinhtrang = self.te_TinhTrang_TuyenDung_DSCongViec.text()

        if (tencongviec == '' or mota == '' or vitrituyendung == '' or trinhdo == '' or loaicongviec == '' or
                chitieu == '' or luong == '' or tinhtrang == ''):
            QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Bạn không được để trống")
        else:
            try:
                file = open("manguoidung.txt", "r")
                manguoidung = str(file.read().strip())
                file.close()

                mydb = mysql.connector.connect(
                    host="localhost",
                    user="root",
                    password="",
                    database="quanlygiaodichvieclam"
                )
                mycursor = mydb.cursor()

                sql = "SELECT manhatuyendung FROM nhatuyendung WHERE manguoidung LIKE %s;"
                val = (manguoidung,)
                mycursor.execute(sql, val)
                result = mycursor.fetchone()

                if result:
                    manhatuyendung = result[0]
                    mycursor.execute(
                        "INSERT INTO congviec ("
                        "manhatuyendung, trinhdohocvan, tencongviec, "
                        "loaicongviec, chitieu, songuoiungtuyen, mota, vitri, tinhtrang, luong) "
                        "VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)",
                        (manhatuyendung, trinhdo, tencongviec, loaicongviec, chitieu, "0",
                         mota, vitrituyendung, tinhtrang, luong))
                    mydb.commit()
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Thêm thành công.")
                    self.loaddata()
                else:
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo",
                                                      "Thêm thất bại, không thể lấy ID người dùng.")

                mycursor.close()
                mydb.close()
                self.te_MaCongViec_TuyenDung_DSCongViec.setText("")
                self.te_TenCongViec_TuyenDung_DSCongViec.setText("")
                self.te_MoTa_TuyenDung_DSCongViec.setText("")
                self.te_ViTri_TuyenDung_DSCongViec.setText("")
                self.Te_TrinhDo_TuyenDung_DSCongViec.setText("")
                self.te_LoaiCongViec_TuyenDung_DSCongViec.setText("")
                self.te_ChiTieu_TuyenDung_DSCongViec.setText("")
                self.te_Luong_TuyenDung_DSCongViec.setText("")
                self.te_TinhTrang_TuyenDung_DSCongViec.setText("")
            except mysql.connector.Error as err:
                print("Error:", err)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi thêm: {err}")
            except Exception as e:
                print("Error:", e)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi thêm: {e}")

    def suaCongViec(self):
        macongviec = self.te_MaCongViec_TuyenDung_DSCongViec.text()
        tencongviec = self.te_TenCongViec_TuyenDung_DSCongViec.text()
        mota = self.te_MoTa_TuyenDung_DSCongViec.text()
        vitrituyendung = self.te_ViTri_TuyenDung_DSCongViec.text()
        trinhdo = self.Te_TrinhDo_TuyenDung_DSCongViec.text()
        loaicongviec = self.te_LoaiCongViec_TuyenDung_DSCongViec.text()
        chitieu = self.te_ChiTieu_TuyenDung_DSCongViec.text()
        luong = self.te_Luong_TuyenDung_DSCongViec.text()
        tinhtrang = self.te_TinhTrang_TuyenDung_DSCongViec.text()

        if (macongviec == '' or tencongviec == '' or mota == '' or vitrituyendung == '' or trinhdo == '' or
                loaicongviec == '' or chitieu == '' or luong == '' or tinhtrang == ''):
            QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Bạn không được để trống")
        else:
            try:
                file = open("manguoidung.txt", "r")
                manguoidung = str(file.read().strip())
                file.close()

                mydb = mysql.connector.connect(
                    host="localhost",
                    user="root",
                    password="",
                    database="quanlygiaodichvieclam"
                )
                mycursor = mydb.cursor()

                sql = "SELECT manhatuyendung FROM nhatuyendung WHERE manguoidung LIKE %s;"
                val = (manguoidung,)
                mycursor.execute(sql, val)
                result = mycursor.fetchone()

                if result:
                    manhatuyendung = result[0]
                    mycursor.execute(
                        "UPDATE congviec SET manhatuyendung = %s, trinhdohocvan = %s, tencongviec = %s, mota = %s, "
                        "vitri = %s, tinhtrang = %s, luong = %s, loaicongviec = %s, chitieu= %s"
                        "WHERE macongviec = %s;",
                        (manhatuyendung, trinhdo, tencongviec, mota, vitrituyendung, tinhtrang,
                         luong, loaicongviec, chitieu, macongviec))
                    mydb.commit()
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Sửa thành công.")
                    self.loaddata()
                else:
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo",
                                                      "Sửa thất bại, không thể lấy ID người dùng.")

                mycursor.close()
                mydb.close()
                self.te_MaCongViec_TuyenDung_DSCongViec.setText("")
                self.te_TenCongViec_TuyenDung_DSCongViec.setText("")
                self.te_MoTa_TuyenDung_DSCongViec.setText("")
                self.te_ViTri_TuyenDung_DSCongViec.setText("")
                self.Te_TrinhDo_TuyenDung_DSCongViec.setText("")
                self.te_LoaiCongViec_TuyenDung_DSCongViec.setText("")
                self.te_ChiTieu_TuyenDung_DSCongViec.setText("")
                self.te_Luong_TuyenDung_DSCongViec.setText("")
                self.te_TinhTrang_TuyenDung_DSCongViec.setText("")
            except mysql.connector.Error as err:
                print("Error:", err)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi thêm: {err}")
            except Exception as e:
                print("Error:", e)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi thêm: {e}")

    def xoaCongViec(self):
        macongviec = self.te_MaCongViec_TuyenDung_DSCongViec.text()
        if macongviec == '':
            QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Bạn không được để trống mã công việc.")
        else:
            try:
                mydb = mysql.connector.connect(
                    host="localhost",
                    user="root",
                    password="",
                    database="quanlygiaodichvieclam"
                )
                mycursor = mydb.cursor()
                sql = "DELETE FROM chitietungtuyen WHERE macongviec = %s"
                val = (macongviec,)
                mycursor.execute(sql, val)
                mydb.commit()

                sql = "DELETE FROM congviec WHERE macongviec = %s"
                val = (macongviec,)
                mycursor.execute(sql, val)
                mydb.commit()

                if mycursor.rowcount == 0:
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo",
                                                      "Không tìm thấy mã công việc để xóa.")
                else:
                    QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", "Xóa thành công.")
                    self.loaddata()
                mycursor.close()
                mydb.close()

                # Clear the input fields
                self.te_MaCongViec_TuyenDung_DSCongViec.setText("")
                self.te_TenCongViec_TuyenDung_DSCongViec.setText("")
                self.te_MoTa_TuyenDung_DSCongViec.setText("")
                self.te_ViTri_TuyenDung_DSCongViec.setText("")
                self.Te_TrinhDo_TuyenDung_DSCongViec.setText("")
                self.te_LoaiCongViec_TuyenDung_DSCongViec.setText("")
                self.te_ChiTieu_TuyenDung_DSCongViec.setText("")
                self.te_Luong_TuyenDung_DSCongViec.setText("")
                self.te_TinhTrang_TuyenDung_DSCongViec.setText("")
            except mysql.connector.Error as err:
                print("Error:", err)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi xóa: {err}")
            except Exception as e:
                print("Error:", e)
                QtWidgets.QMessageBox.information(TuyenDung_DSCongViec, "Thông báo", f"Có lỗi xảy ra khi xóa: {e}")

    def loaddata(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )

            mycursor = mydb.cursor()
            file = open("manhatuyendung.txt", "r")
            manhatuyendung = str(file.read())
            file.close()
            mycursor.execute("SELECT * FROM congviec WHERE  manhatuyendung = %s", (manhatuyendung, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))

            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")

    def chuyenDenPheDuyet(self):
        macongviec = self.te_MaCongViec_TuyenDung_DSCongViec.text()
        file = open("macongviec.txt", "w")
        file.write(str(macongviec))
        file.close()
        self.te_MaCongViec_TuyenDung_DSCongViec.setText('')
        subprocess.run(["python", "pheduyet.py"])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TuyenDung_DSCongViec = QtWidgets.QWidget()
    ui = Ui_TuyenDung_DSCongViec()
    ui.setupUi(TuyenDung_DSCongViec)
    TuyenDung_DSCongViec.show()
    sys.exit(app.exec())
