# Form implementation generated from reading ui file 'tuyendung.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import subprocess
from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox
import mysql.connector


class Ui_NhaTuyenDung(object):
    def chuyenDenQuanLyCongViec(self):
        subprocess.run(["python", "tuyendung_QuanLyCongViec.py"])

    def chuyenDenDanhSachNguoiTimViec(self):
        subprocess.run(["python", "tuyendung_QuanLyNguoiTimViec.py"])

    def chuyenDenTrangChu(self):
        NhaTuyenDung.destroy()
        subprocess.run(["python", "trangchu.py"])

    def setupUi(self, NhaTuyenDung):
        NhaTuyenDung.setObjectName("NhaTuyenDung")
        NhaTuyenDung.resize(373, 345)
        self.centralwidget = QtWidgets.QWidget(parent=NhaTuyenDung)
        self.centralwidget.setObjectName("centralwidget")
        self.bt_listnguoitimviec = QtWidgets.QPushButton(parent=self.centralwidget,
                                                         clicked=lambda: self.chuyenDenDanhSachNguoiTimViec())
        self.bt_listnguoitimviec.setGeometry(QtCore.QRect(80, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_listnguoitimviec.setFont(font)
        self.bt_listnguoitimviec.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_listnguoitimviec.setObjectName("bt_listnguoitimviec")
        self.bt_thoat = QtWidgets.QPushButton(parent=NhaTuyenDung, clicked=lambda: self.chuyenDenTrangChu())
        self.bt_thoat.setGeometry(QtCore.QRect(80, 240, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_thoat.setFont(font)
        self.bt_thoat.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_thoat.setObjectName("bt_thoat")
        self.bt_listcongviec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_listcongviec.setGeometry(QtCore.QRect(80, 100, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_listcongviec.setFont(font)
        self.bt_listcongviec.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_listcongviec.setObjectName("bt_listcongviec")
        self.bt_thongbao = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_thongbao.setGeometry(QtCore.QRect(80, 170, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bt_thongbao.setFont(font)
        self.bt_thongbao.setStyleSheet("background-color: rgb(0, 170, 255);")
        self.bt_thongbao.setObjectName("bt_thongbao")
        NhaTuyenDung.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=NhaTuyenDung)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 26))
        self.menubar.setObjectName("menubar")
        NhaTuyenDung.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=NhaTuyenDung)
        self.statusbar.setObjectName("statusbar")
        NhaTuyenDung.setStatusBar(self.statusbar)

        self.retranslateUi(NhaTuyenDung)
        QtCore.QMetaObject.connectSlotsByName(NhaTuyenDung)
        self.bt_thongbao.clicked.connect(self.thongBao)
        self.bt_listcongviec.clicked.connect(self.chuyenDenQuanLyCongViec)

    def retranslateUi(self, NhaTuyenDung):
        _translate = QtCore.QCoreApplication.translate
        NhaTuyenDung.setWindowTitle(_translate("NhaTuyenDung", "Tuyển dụng"))
        self.bt_listnguoitimviec.setText(_translate("NhaTuyenDung", "Người tìm việc"))
        self.bt_thoat.setText(_translate("NhaTuyenDung", "Thoát"))
        self.bt_listcongviec.setText(_translate("NhaTuyenDung", "Công việc"))
        self.bt_thongbao.setText(_translate("NhaTuyenDung", "Thông báo"))

    def thongBao(self):
        subprocess.run(["python", "thongbao.py"])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    NhaTuyenDung = QtWidgets.QMainWindow()
    ui = Ui_NhaTuyenDung()
    ui.setupUi(NhaTuyenDung)
    NhaTuyenDung.show()
    sys.exit(app.exec())
