# Form implementation generated from reading ui file 'tuyendung_QuanLyNguoiTimViec.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import subprocess
import mysql.connector


class Ui_TuyenDung_DSNguoiTimViec(object):
    def setupUi(self, TuyenDung_DSNguoiTimViec):
        TuyenDung_DSNguoiTimViec.setObjectName("TuyenDung_DSNguoiTimViec")
        TuyenDung_DSNguoiTimViec.resize(703, 477)
        self.centralwidget = QtWidgets.QWidget(parent=TuyenDung_DSNguoiTimViec)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 10, 321, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.table_dsCongViec = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table_dsCongViec.setGeometry(QtCore.QRect(80, 140, 531, 171))
        self.table_dsCongViec.setObjectName("table_dsCongViec")
        self.table_dsCongViec.setColumnCount(5)
        self.table_dsCongViec.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_dsCongViec.setItem(0, 1, item)
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 350, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.te_TimKiemTheoTenNTV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_TimKiemTheoTenNTV.setGeometry(QtCore.QRect(240, 70, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.te_TimKiemTheoTenNTV.setFont(font)
        self.te_TimKiemTheoTenNTV.setObjectName("te_TimKiemTheoTenNTV")
        self.bt_XemChiTietCongViec_DSCongViec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_XemChiTietCongViec_DSCongViec.setGeometry(QtCore.QRect(470, 340, 201, 41))
        self.bt_XemChiTietCongViec_DSCongViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_XemChiTietCongViec_DSCongViec.setObjectName("bt_XemChiTietCongViec_DSCongViec")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 181, 31))
        self.label_2.setObjectName("label_2")
        self.bt_TimKiem_TuyenDung_dsNguoiTimViec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bt_TimKiem_TuyenDung_dsNguoiTimViec.setGeometry(QtCore.QRect(570, 70, 101, 41))
        self.bt_TimKiem_TuyenDung_dsNguoiTimViec.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 255);")
        self.bt_TimKiem_TuyenDung_dsNguoiTimViec.setObjectName("bt_TimKiem_TuyenDung_dsNguoiTimViec")
        self.te_MaNguoiTimViec_TuyenDung_DSCongViec = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.te_MaNguoiTimViec_TuyenDung_DSCongViec.setGeometry(QtCore.QRect(250, 350, 201, 31))
        self.te_MaNguoiTimViec_TuyenDung_DSCongViec.setObjectName("te_MaNguoiTimViec_TuyenDung_DSCongViec")
        TuyenDung_DSNguoiTimViec.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=TuyenDung_DSNguoiTimViec)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 703, 26))
        self.menubar.setObjectName("menubar")
        TuyenDung_DSNguoiTimViec.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=TuyenDung_DSNguoiTimViec)
        self.statusbar.setObjectName("statusbar")
        TuyenDung_DSNguoiTimViec.setStatusBar(self.statusbar)

        self.retranslateUi(TuyenDung_DSNguoiTimViec)
        QtCore.QMetaObject.connectSlotsByName(TuyenDung_DSNguoiTimViec)

        self.bt_TimKiem_TuyenDung_dsNguoiTimViec.clicked.connect(self.timNguoiTimViecTheoTen)
        self.bt_XemChiTietCongViec_DSCongViec.clicked.connect(self.chuyenDenThongTinNTV)
        self.loaddata()


    def retranslateUi(self, TuyenDung_DSNguoiTimViec):
        _translate = QtCore.QCoreApplication.translate
        TuyenDung_DSNguoiTimViec.setWindowTitle(_translate("TuyenDung_DSNguoiTimViec", "Tuyển Dụng - Danh Sách Người Tìm Việc"))
        self.label.setText(_translate("TuyenDung_DSNguoiTimViec", "<html><head/><body><p><span style=\" font-size:18pt;\">Quản lý người tìm việc</span></p></body></html>"))
        item = self.table_dsCongViec.horizontalHeaderItem(0)
        item.setText(_translate("TuyenDung_DSNguoiTimViec", "Mã"))
        item = self.table_dsCongViec.horizontalHeaderItem(1)
        item.setText(_translate("TuyenDung_DSNguoiTimViec", "Tên"))
        item = self.table_dsCongViec.horizontalHeaderItem(2)
        item.setText(_translate("TuyenDung_DSNguoiTimViec", "Số điện thoại"))
        item = self.table_dsCongViec.horizontalHeaderItem(3)
        item.setText(_translate("TuyenDung_DSNguoiTimViec", "Mail"))
        item = self.table_dsCongViec.horizontalHeaderItem(4)
        item.setText(_translate("TuyenDung_DSNguoiTimViec", "Thành phố"))
        __sortingEnabled = self.table_dsCongViec.isSortingEnabled()
        self.table_dsCongViec.setSortingEnabled(False)
        self.table_dsCongViec.setSortingEnabled(__sortingEnabled)
        self.label_11.setText(_translate("TuyenDung_DSNguoiTimViec", "Mã người tìm việc"))
        self.bt_XemChiTietCongViec_DSCongViec.setText(_translate("TuyenDung_DSNguoiTimViec", "Xem chi tiết hồ sơ"))
        self.label_2.setText(_translate("TuyenDung_DSNguoiTimViec", "<html><head/><body><p><span style=\" font-size:12pt;\">Tên người tìm việc</span></p></body></html>"))
        self.bt_TimKiem_TuyenDung_dsNguoiTimViec.setText(_translate("TuyenDung_DSNguoiTimViec", "Tìm kiếm"))

    def timNguoiTimViecTheoTen(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            tennguoitimviec = self.te_TimKiemTheoTenNTV.text()
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manguoitimviec, ten, sdt, mail, thanhpho FROM nguoitimviec WHERE ten like %s",
                             (tennguoitimviec, ))
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))
            self.te_TimKiemTheoTenNTV.setText("")
            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
            self.te_TimKiemTheoTenNTV.setText("")
        except Exception as e:
            print(f"Error: {e}")
            self.te_TimKiemTheoTenNTV.setText("")

    def loaddata(self):
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manguoitimviec, ten, sdt, mail, thanhpho FROM nguoitimviec")
            rows = mycursor.fetchall()
            col_count = len(mycursor.description)

            self.table_dsCongViec.setColumnCount(col_count)
            self.table_dsCongViec.setRowCount(len(rows))

            for tablerow, row in enumerate(rows):
                for col in range(col_count):
                    self.table_dsCongViec.setItem(tablerow, col, QtWidgets.QTableWidgetItem(str(row[col])))

            mycursor.close()
            mydb.close()
        except Error as e:
            print(f"Database error: {e}")
        except Exception as e:
            print(f"Error: {e}")

    def chuyenDenThongTinNTV(self):
        manguoitimviec = self.te_MaNguoiTimViec_TuyenDung_DSCongViec.text()
        file = open("manguoitimviec.txt", "w")
        file.write(str(manguoitimviec))
        file.close()
        subprocess.run(["python", "tuyendung_ThongTinNguoiTimViec.py"])
        self.te_MaNguoiTimViec_TuyenDung_DSCongViec.setText("")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TuyenDung_DSNguoiTimViec = QtWidgets.QMainWindow()
    ui = Ui_TuyenDung_DSNguoiTimViec()
    ui.setupUi(TuyenDung_DSNguoiTimViec)
    TuyenDung_DSNguoiTimViec.show()
    sys.exit(app.exec())
