# Form implementation generated from reading ui file 'tuyendung_ThongTinNguoiTimViec.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import mysql.connector


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 517)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 60, 711, 161))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.li_TTNguoiTimViec_TuyenDung = QtWidgets.QListView(parent=self.groupBox)
        self.li_TTNguoiTimViec_TuyenDung.setGeometry(QtCore.QRect(20, 30, 671, 111))
        self.li_TTNguoiTimViec_TuyenDung.setObjectName("li_TTNguoiTimViec_TuyenDung")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 240, 711, 221))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.li_HSNguoiTimViec_TuyenDung = QtWidgets.QListView(parent=self.groupBox_2)
        self.li_HSNguoiTimViec_TuyenDung.setGeometry(QtCore.QRect(20, 30, 671, 171))
        self.li_HSNguoiTimViec_TuyenDung.setObjectName("li_HSNguoiTimViec_TuyenDung")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.loadThongTin()
        self.loadHoSo()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "THÔNG TIN NGƯỜI TÌM VIỆC"))
        self.groupBox.setTitle(_translate("MainWindow", "I. THÔNG TIN CHUNG"))
        self.groupBox_2.setTitle(_translate("MainWindow", "II. THÔNG TIN HỒ SƠ"))

    def loadThongTin(self):
        file = open("manguoitimviec.txt", "r")
        manguoitimviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT manguoitimviec, ten, sdt, mail, thanhpho FROM nguoitimviec "
                             "WHERE manguoitimviec = %s", (manguoitimviec,))
            cttt = mycursor.fetchall()

            thongtin = ["Mã người tìm việc: ", "Tên: ", "Số điện thoại: ", "Mail: ", "Thành phố: "]

            if cttt:
                thongtin = [f"{thongtin[i]}{cttt[0][i]}" for i in range(len(thongtin))]

            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in thongtin:
                item = QtGui.QStandardItem(info)
                model.appendRow(item)
            self.li_TTNguoiTimViec_TuyenDung.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")

    def loadHoSo(self):
        file = open("manguoitimviec.txt", "r")
        manguoitimviec = str(file.read().strip())
        file.close()
        try:
            mydb = mysql.connector.connect(
                host="localhost",
                user="root",
                password="",
                database="quanlygiaodichvieclam"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT "
                             "kinhnghiemlamviec, trinhdohocvan, hoatdong, giaykhen, duan, chungchi, gioitinh "
                             "FROM hoso "
                             "WHERE manguoitimviec = %s", (manguoitimviec,))
            cttt = mycursor.fetchall()

            thongtin = ["Kinh nghiệm làm việc: ", "Trình độ học vấn: ", "Hoạt đông: ", "Giấy khen: ", "Dự án: "
                        , "Chứng chỉ: ", "Giới tính: "]

            if cttt:
                thongtin = [f"{thongtin[i]}{cttt[0][i]}" for i in range(len(thongtin))]

            mycursor.close()
            mydb.close()

            # Thêm từng thông tin vào hộp danh sách
            model = QtGui.QStandardItemModel()
            for info in thongtin:
                item = QtGui.QStandardItem(info)
                model.appendRow(item)
            self.li_HSNguoiTimViec_TuyenDung.setModel(model)

        except mysql.connector.Error as e:
            print(f"Lỗi cơ sở dữ liệu: {e}")
        except Exception as e:
            print(f"Lỗi: {e}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
